name: GitHub Pages CI/CD

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Deploy to GitHub Pages using PAT
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PAT_TOKEN }}  # Uses the secret you created
          publish_dir: ./   # Root directory contains index.html
          commit_message: "Auto deploy To-Do List via GitHub Actions"
