name: Deploy To-Do List to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install gh-pages package
      - name: Install gh-pages
        run: npm install -g gh-pages

      # Step 4: Deploy to GitHub Pages
      - name: Deploy
        run: gh-pages -d ./ -b gh-pages -r https://github.com/${{ github.repository }}.git
